import streamlit as st
import joblib
import numpy as np
# No need for 'requests', 'os', 'pathlib' for image display anymore with base64
# from PIL import Image # PIL (Pillow) is not directly used for st.image, so it can be commented out if not needed elsewhere

# Load the trained model and label encoder
# IMPORTANT: Ensure these files ('character_predictor.pkl', 'label_encoder.pkl')
# are in the same directory as app.py on your deployment platform (e.g., GitHub repo).
try:
    model = joblib.load("character_predictor.pkl")
    le = joblib.load("label_encoder.pkl")
except FileNotFoundError as e:
    st.error(f"Error loading model or label encoder: {e}. "
             "Please ensure 'character_predictor.pkl' and 'label_encoder.pkl' "
             "are in the correct path on your deployment server.")
    st.stop() # Stop the app execution if essential files are missing

# Set Streamlit page configuration (must be called once at the top of the script)
st.set_page_config(page_title="Which Famous Character Are You?", layout="centered")

# --- Background Color Management ---
# Define a default background color for the app's initial state.
# This color is chosen to be clearly non-white and provide good contrast for questions.
DEFAULT_BACKGROUND_COLOR = "#2c3e50" # Dark slate grey/charcoal
DEFAULT_TEXT_COLOR = "white" # Text color for default dark background

# Function to set dynamic background color for the whole app
def set_background_color(hex_color, text_color):
    st.markdown(
        f"""
        <style>
        .stApp {{
            background-color: {hex_color};
            color: {text_color}; /* Set text color based on background for readability */
        }}
        /* Ensure specific elements like headers and bold text also inherit or have good contrast */
        h1, h2, h3, h4, h5, h6, strong {{
            color: {text_color};
        }}
        /* For the selectbox labels which are bold markdown */
        .stSelectbox label p strong {{
            color: {text_color};
        }}
        /* Text inputs and other elements might need specific styling if they don't inherit well */
        div[data-testid="stTextInput"] > label > div > p,
        div[data-testid="stTextarea"] > label > div > p {{
            color: {text_color};
        }}
        /* General paragraph text */
        .stMarkdown p {{
            color: {text_color};
        }}
        </style>
        """,
        unsafe_allow_html=True # Required to inject custom HTML/CSS
    )

# Dictionary mapping characters to their specific background colors.
# Most of these are light, so we'll set their text color to black.
color_map = {
    "Walter White": {"bg": "#F4D03F", "text": "black"},  # Yellowish
    "Michael Scott": {"bg": "#D6EAF8", "text": "black"}, # Light Blue
    "Nezuko": {"bg": "#F9EBEA", "text": "black"},      # Light Pink/Beige
    "Sheldon Cooper": {"bg": "#E8DAEF", "text": "black"}, # Light Purple
    "Johan Liebert": {"bg": "#FADBD8", "text": "black"},  # Light Peach
    "Moira Rose": {"bg": "#FCF3CF", "text": "black"},    # Creamy Yellow
    "Phil Dunphy": {"bg": "#D1F2EB", "text": "black"},    # Light Teal
    "Cameron Tucker": {"bg": "#FADBD8", "text": "black"}, # Light Peach
    "Ron Swanson": {"bg": "#FDEDEC", "text": "black"},    # Light Red/Orange
    "Sherlock Holmes": {"bg": "#EAECEE", "text": "black"},# Light Grey
    "Batman": {"bg": "#D5DBDB", "text": "black"},       # Grey
    "Peter Griffin": {"bg": "#F6DDCC", "text": "black"},  # Light Orange
    "Daenerys": {"bg": "#EBDEF0", "text": "black"},     # Lavender
    "Andy Dwyer": {"bg": "#FEF9E7", "text": "black"},    # Pale Yellow
    "Jethalal Gada": {"bg": "#FCF3CF", "text": "black"}, # Creamy Yellow
    "Chandler Bing": {"bg": "#E8F8F5", "text": "black"}  # Mint Green
}

# --- Paste the BASE64_IMAGES dictionary generated by generate_base64.py HERE ---
# Example format (your actual strings will be much longer):
# BASE64_IMAGES = {
#     "Walter White": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=",
#     "Sheldon Cooper": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=",
#     # ... and so on for all your characters
# }
# Make sure to copy the entire dictionary including the 'BASE64_IMAGES = {' and '}'
# and paste it below this comment block.

# Example placeholder if you haven't run generate_base64.py yet:
BASE64_IMAGES = {
    "Sheldon Cooper": "[https://placehold.co/300x300/cccccc/ffffff?text=Run+Local+Script+For+Images](https://placehold.co/300x300/cccccc/ffffff?text=Run+Local+Script+For+Images)",
    "Batman": "[https://placehold.co/300x300/cccccc/ffffff?text=Run+Local+Script+For+Images](https://placehold.co/300x300/cccccc/ffffff?text=Run+Local+Script+For+Images)",
    # Add other characters if you want placeholders for them or after generating
}


# Define the questions for the personality quiz
questions = [
    "🧠 On a scale of 1 to 3, how calm are you under pressure?",
    "🎉 On a scale of 1 to 3, how much do you enjoy wild, energetic fun over quiet time?",
    "🤔 On a scale of 1 to 3, how impulsive are your decisions?",
    "😨 On a scale of 1 to 3, how strongly do you fear losing control or power?",
    "🪞 On a scale of 1 to 3, how emotional and expressive are you?",
    "🧑‍🤝‍🧑 On a scale of 1 to 3, how much of a leader are you in group settings?",
    "🔪 On a scale of 1 to 3, how intensely do you react to betrayal?",
    "⚖️ On a scale of 1 to 3, how much do you value logic over emotions in life?",
    "🐶 On a scale of 1 to 3, how affectionate and attached are you to animals or pets?",
    "👗 On a scale of 1 to 3, how stylish and expressive is your dressing style?",
    "🛠️ On a scale of 1 to 3, how much do you prefer hands-on, practical work over theoretical?",
    "🗣️ On a scale of 1 to 3, how much do people find you socially funny or talkative?",
    "💔 On a scale of 1 to 3, how deeply do you hold grudges when someone hurts you?",
    "🫶 On a scale of 1 to 3, how much do you admire honesty and kindness in others?",
    "✈️ On a scale of 1 to 3, how much do you crave a peaceful, scenic vacation over a luxurious one?"
]

# Options for the selectbox inputs
options = ["1", "2", "3"]

# --- Streamlit UI Layout ---

# Apply the initial default background and text color when the app first loads
set_background_color(DEFAULT_BACKGROUND_COLOR, DEFAULT_TEXT_COLOR)

st.title("🧠 Which Famous Character Are You?")
st.write("Answer the questions below and find out which iconic character you're most like!")
st.write("1 means you are GREAT at it, 2 means you are AVERAGE at it and 3 means you are poor at it!")
st.write("Be honest :)")

answers = []
for idx, question in enumerate(questions):
    answer = st.selectbox(f"**{question}**", options, key=idx)
    answers.append(int(answer))

# Button to trigger the character prediction
if st.button("✨ Reveal Your Character"):
    input_data = np.array(answers).reshape(1, -1)
    prediction = model.predict(input_data)
    character = le.inverse_transform(prediction)[0]

    colors = color_map.get(character, {"bg": DEFAULT_BACKGROUND_COLOR, "text": DEFAULT_TEXT_COLOR})
    set_background_color(colors["bg"], colors["text"])
    
    st.subheader(f"🎉 You are most like **{character}**!")

    # Get the base64 image data for the predicted character
    image_data_url = BASE64_IMAGES.get(character)
    
    if image_data_url:
        # Use st.markdown() with the base64 data directly in the <img> tag
        # The onerror is technically not needed here as data: URLs don't "fail to load" in the same way,
        # but leaving it for robustness or if you revert to external URLs later.
        st.markdown(
            f"""
            <div style="display: flex; justify-content: center; margin-bottom: 10px;">
                <img src="{image_data_url}" 
                     alt="Image for {character}" 
                     style="max-width: 100%; height: auto; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
            </div>
            <p style="text-align: center; font-size: 1.2em; font-weight: bold;">{character}</p>
            """,
            unsafe_allow_html=True
        )
    else:
        # Fallback if character's base64 data is not found in BASE64_IMAGES
        st.warning(f"Image data for {character} not found in embedded resources. Displaying placeholder.")
        st.markdown(
            f"""
            <div style="display: flex; justify-content: center; margin-bottom: 10px;">
                <img src="[https://placehold.co/300x300/cccccc/ffffff?text=Image+Missing](https://placehold.co/300x300/cccccc/ffffff?text=Image+Missing)" 
                     alt="Image missing" 
                     style="max-width: 100%; height: auto; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.2); 
                            background-color: #f0f0f0; padding: 10px; border: 1px solid #ddd;">
            </div>
            <p style="text-align: center; font-size: 1.2em; font-weight: bold;">{character}</p>
            """,
            unsafe_allow_html=True
        )

