import streamlit as st
import joblib
import numpy as np

# Load the trained model and label encoder
try:
    model = joblib.load("character_predictor.pkl")
    le = joblib.load("label_encoder.pkl")
except FileNotFoundError as e:
    st.error(f"Error loading model or label encoder: {e}. "
             "Please ensure 'character_predictor.pkl' and 'label_encoder.pkl' "
             "are in the correct path on your deployment server.")
    st.stop()

# Set Streamlit page configuration
st.set_page_config(page_title="Which Famous Character Are You?", layout="centered")

# --- Background Color Management ---
DEFAULT_BACKGROUND_COLOR = "#2c3e50" # Dark slate grey/charcoal
DEFAULT_TEXT_COLOR = "white" # Text color for default dark background

def set_background_color(hex_color, text_color):
    st.markdown(
        f"""
        <style>
        .stApp {{
            background-color: {hex_color};
            color: {text_color}; /* Set text color based on background for readability */
        }}
        h1, h2, h3, h4, h5, h6, strong {{
            color: {text_color};
        }}
        .stSelectbox label p strong {{
            color: {text_color};
        }}
        div[data-testid="stTextInput"] > label > div > p,
        div[data-testid="stTextarea"] > label > div > p {{
            color: {text_color};
        }}
        .stMarkdown p {{
            color: {text_color};
        }}
        </style>
        """,
        unsafe_allow_html=True
    )

color_map = {
    "Walter White": {"bg": "#F4D03F", "text": "black"},
    "Michael Scott": {"bg": "#D6EAF8", "text": "black"},
    "Nezuko": {"bg": "#F9EBEA", "text": "black"},
    "Sheldon Cooper": {"bg": "#E8DAEF", "text": "black"},
    "Johan Liebert": {"bg": "#FADBD8", "text": "black"},
    "Moira Rose": {"bg": "#FCF3CF", "text": "black"},
    "Phil Dunphy": {"bg": "#D1F2EB", "text": "black"},
    "Cameron Tucker": {"bg": "#FADBD8", "text": "black"},
    "Ron Swanson": {"bg": "#FDEDEC", "text": "black"},
    "Sherlock Holmes": {"bg": "#EAECEE", "text": "black"},
    "Batman": {"bg": "#D5DBDB", "text": "black"},
    "Peter Griffin": {"bg": "#F6DDCC", "text": "black"},
    "Daenerys": {"bg": "#EBDEF0", "text": "black"},
    "Andy Dwyer": {"bg": "#FEF9E7", "text": "black"},
    "Jethalal Gada": {"bg": "#FCF3CF", "text": "black"},
    "Chandler Bing": {"bg": "#E8F8F5", "text": "black"}
}

# --- IMPORTANT: Paste the BASE64_IMAGES dictionary generated by generate_base64.py HERE ---
# REPLACE the following placeholder dictionary with your actual generated one:
BASE64_IMAGES = {
    "Andy Dwyer": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Batman": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Cameron Tucker": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Chandler Bing": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Daenerys": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Jethalal Gada": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Johan Liebert": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Michael Scott": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Moira Rose": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Nezuko": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Peter Griffin": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Phil Dunphy": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Ron Swanson": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Sheldon Cooper": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Sherlock Holmes": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
    "Walter White": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQMAAABcdgIBAAAABlBMVEX///8AAABVwtS5AAAAFUlEQVR42u3QMQEAAAEAIL/1eAM0F/43AAAAAABgXgB534/4AAAAAElFTkSuQmCC",
}


questions = [
    "🧠 On a scale of 1 to 3, how calm are you under pressure?",
    "🎉 On a scale of 1 to 3, how much do you enjoy wild, energetic fun over quiet time?",
    "🤔 On a scale of 1 to 3, how impulsive are your decisions?",
    "😨 On a scale of 1 to 3, how strongly do you fear losing control or power?",
    "🪞 On a scale of 1 to 3, how emotional and expressive are you?",
    "🧑‍🤝‍🧑 On a scale of 1 to 3, how much of a leader are you in group settings?",
    "🔪 On a scale of 1 to 3, how intensely do you react to betrayal?",
    "⚖️ On a scale of 1 to 3, how much do you value logic over emotions in life?",
    "🐶 On a scale of 1 to 3, how affectionate and attached are you to animals or pets?",
    "👗 On a scale of 1 to 3, how stylish and expressive is your dressing style?",
    "🛠️ On a scale of 1 to 3, how much do you prefer hands-on, practical work over theoretical?",
    "🗣️ On a scale of 1 to 3, how much do people find you socially funny or talkative?",
    "💔 On a scale of 1 to 3, how deeply do you hold grudges when someone hurts you?",
    "🫶 On a scale of 1 to 3, how much do you admire honesty and kindness in others?",
    "✈️ On a scale of 1 to 3, how much do you crave a peaceful, scenic vacation over a luxurious one?"
]

options = ["1", "2", "3"]

# --- Streamlit UI Layout ---
set_background_color(DEFAULT_BACKGROUND_COLOR, DEFAULT_TEXT_COLOR)

st.title("🧠 Which Famous Character Are You?")
st.write("Answer the questions below and find out which iconic character you're most like!")
st.write("1 means you are GREAT at it, 2 means you are AVERAGE at it and 3 means you are poor at it!")
st.write("Be honest :)")

answers = []
for idx, question in enumerate(questions):
    answer = st.selectbox(f"**{question}**", options, key=idx)
    answers.append(int(answer))

if st.button("✨ Reveal Your Character"):
    input_data = np.array(answers).reshape(1, -1)
    prediction = model.predict(input_data)
    character = le.inverse_transform(prediction)[0]

    colors = color_map.get(character, {"bg": DEFAULT_BACKGROUND_COLOR, "text": DEFAULT_TEXT_COLOR})
    set_background_color(colors["bg"], colors["text"])
    
    st.subheader(f"🎉 You are most like **{character}**!")

    # --- DIAGNOSTIC PRINT ---
    st.info(f"Predicted character from model: '{character}'")
    
    # Get the base64 image data for the predicted character
    image_data_url = BASE64_IMAGES.get(character) # Use .get() to avoid KeyError directly

    # --- NEW DIAGNOSTIC PRINT for Base64 String ---
    if image_data_url:
        st.info(f"Base64 string for '{character}' starts with: '{image_data_url[:50]}...'") # Print first 50 chars
    else:
        st.warning(f"No Base64 data found in dictionary for '{character}'.")


    if image_data_url and image_data_url.startswith("data:image/png;base64,"): # Basic sanity check
        st.markdown(
            f"""
            <div style="display: flex; justify-content: center; margin-bottom: 10px;">
                <img src="{image_data_url}" 
                     alt="Image for {character}" 
                     style="max-width: 100%; height: auto; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
            </div>
            <p style="text-align: center; font-size: 1.2em; font-weight: bold;">{character}</p>
            """,
            unsafe_allow_html=True
        )
    else:
        # Fallback if character's base64 data is not found OR if it's malformed
        st.error(f"Image data for '{character}' is missing or malforAmed. "
                 "Please ensure the `BASE64_IMAGES` dictionary is correctly copied and contains valid Base64 for this character.")
        st.markdown(
            f"""
            <div style="display: flex; justify-content: center; margin-bottom: 10px;">
                <img src="[https://placehold.co/300x300/cccccc/ffffff?text=Image+Missing](https://placehold.co/300x300/cccccc/ffffff?text=Image+Missing)" 
                     alt="Image missing" 
                     style="max-width: 100%; height: auto; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.2); 
                            background-color: #f0f0f0; padding: 10px; border: 1px solid #ddd;">
            </div>
            <p style="text-align: center; font-size: 1.2em; font-weight: bold;">{character}</p>
            """,
            unsafe_allow_html=True
        )

